package com.trkgrn_theomer.bigdatathresholding.ui.threshold;

import com.trkgrn_theomer.bigdatathresholding.api.model.concretes.Complaint;
import com.trkgrn_theomer.bigdatathresholding.api.model.dtos.Threshold;
import com.trkgrn_theomer.bigdatathresholding.api.service.ComplaintService;
import com.trkgrn_theomer.bigdatathresholding.api.thread.ThresholdThread;
import com.trkgrn_theomer.bigdatathresholding.api.utility.StringUtil;
import com.trkgrn_theomer.bigdatathresholding.api.utility.TableUtil;
import com.trkgrn_theomer.bigdatathresholding.api.utility.ThreadUtil;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author trkgrn&&omeraran
 */
@Component
public class ThresholdUI extends javax.swing.JFrame {


    private final StringUtil stringUtil;
    private final ComplaintService complaintService;
    private final ThreadUtil threadUtil;
    private final TableUtil tableUtil;
    private static List<Complaint> allData;

    /**
     * Creates new form MainForm
     */
    public ThresholdUI(StringUtil stringUtil, ComplaintService complaintService, ThreadUtil threadUtil, TableUtil tableUtil) {
        this.stringUtil = stringUtil;
        this.complaintService = complaintService;
        this.threadUtil = threadUtil;
        this.tableUtil = tableUtil;
        this.allData = complaintService.getAll();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        threadInfoTable = new javax.swing.JTable();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        buttonS1 = new javax.swing.JButton();
        selectedColumnS1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        thresholdS1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        threadCountS1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        buttonS2 = new javax.swing.JButton();
        selectedColumnS2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        thresholdS2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        selectedColumn2S2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        threshold2S2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        threadCountS2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        choosenColumnS2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        buttonS3 = new javax.swing.JButton();
        selectedColumnS3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        thresholdS3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        threadCountS3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        complaintId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "#", "Kayıt 1", "Kayıt 2", "Benzerlik Oranı"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultTable);
        if (resultTable.getColumnModel().getColumnCount() > 0) {
            resultTable.getColumnModel().getColumn(0).setResizable(false);
            resultTable.getColumnModel().getColumn(1).setResizable(false);
            resultTable.getColumnModel().getColumn(2).setResizable(false);
            resultTable.getColumnModel().getColumn(3).setResizable(false);
        }

        threadInfoTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "#", "Thread ID", "Thread Adı", "Çalışma Süresi"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(threadInfoTable);
        if (threadInfoTable.getColumnModel().getColumnCount() > 0) {
            threadInfoTable.getColumnModel().getColumn(0).setResizable(false);
            threadInfoTable.getColumnModel().getColumn(1).setResizable(false);
            threadInfoTable.getColumnModel().getColumn(2).setResizable(false);
            threadInfoTable.getColumnModel().getColumn(3).setResizable(false);
        }

        buttonS1.setText("Getir");
        buttonS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonS1ActionPerformed(evt);
            }
        });

        selectedColumnS1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Product", "Company", "Issue", "State", "ZIP Code"}));
        selectedColumnS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedColumnS1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Seçilen Sütun:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Benzerlik Oranı:");

        thresholdS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thresholdS1ActionPerformed(evt);
            }
        });
        thresholdS1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                thresholdS1KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Thread Sayısı:");

        threadCountS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threadCountS1ActionPerformed(evt);
            }
        });
        threadCountS1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                threadCountS1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(71, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(37, 37, 37)
                                                .addComponent(thresholdS1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel1))
                                                        .addComponent(jLabel8))
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(selectedColumnS1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(threadCountS1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(74, 74, 74)
                                                                .addComponent(buttonS1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(120, 120, 120))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{selectedColumnS1, thresholdS1});

        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(selectedColumnS1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(thresholdS1))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonS1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(threadCountS1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{selectedColumnS1, thresholdS1});

        jTabbedPane5.addTab("S1", jPanel1);

        buttonS2.setText("Getir");
        buttonS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonS2ActionPerformed(evt);
            }
        });

        selectedColumnS2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Product", "Company", "Issue", "State", "ZIP Code"}));
        selectedColumnS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedColumnS2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Sütun 1:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Benzerlik Oranı:");

        thresholdS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thresholdS2ActionPerformed(evt);
            }
        });
        thresholdS2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                thresholdS2KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Sütun 2:");

        selectedColumn2S2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Product", "Company", "Issue", "State", "ZIP Code"}));
        selectedColumn2S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedColumn2S2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Benzerlik Oranı:");

        threshold2S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threshold2S2ActionPerformed(evt);
            }
        });
        threshold2S2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                threshold2S2KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Thread Sayısı:");

        threadCountS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threadCountS2ActionPerformed(evt);
            }
        });
        threadCountS2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                threadCountS2KeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("İstenen Sütun:");

        choosenColumnS2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Product", "Company", "Issue", "State", "ZIP Code"}));
        choosenColumnS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosenColumnS2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(selectedColumn2S2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addGap(19, 19, 19)
                                                                .addComponent(selectedColumnS2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel7)
                                                .addGap(19, 19, 19)
                                                .addComponent(threadCountS2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(threshold2S2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(thresholdS2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(choosenColumnS2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonS2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{threshold2S2, thresholdS2});

        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(selectedColumnS2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(thresholdS2)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(selectedColumn2S2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(threshold2S2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(choosenColumnS2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(threadCountS2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(buttonS2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{choosenColumnS2, selectedColumn2S2, selectedColumnS2, threshold2S2, thresholdS2});

        jTabbedPane5.addTab("S2", jPanel4);

        buttonS3.setText("Getir");
        buttonS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonS3ActionPerformed(evt);
            }
        });

        selectedColumnS3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Product", "Company", "Issue", "State", "ZIP Code"}));
        selectedColumnS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedColumnS3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Seçilen Sütun:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Benzerlik Oranı:");

        thresholdS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thresholdS3ActionPerformed(evt);
            }
        });
        thresholdS3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                thresholdS3KeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Thread Sayısı:");

        threadCountS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threadCountS3ActionPerformed(evt);
            }
        });
        threadCountS3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                threadCountS3KeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Complaint ID:");

        complaintId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complaintIdActionPerformed(evt);
            }
        });
        complaintId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                complaintIdKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonS3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(thresholdS3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                        .addComponent(selectedColumnS3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(threadCountS3))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(complaintId)))
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{selectedColumnS3, threadCountS3, thresholdS3});

        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(46, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(complaintId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(selectedColumnS3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(thresholdS3)
                                                .addComponent(threadCountS3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addComponent(buttonS3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{selectedColumnS3, threadCountS3, thresholdS3});

        jTabbedPane5.addTab("S3", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonS1ActionPerformed

    private void buttonS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonS2ActionPerformed

    private void buttonS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonS3ActionPerformed
        String selectedComplaintId = complaintId.getText();
        String selectedColumn = selectedColumnS3.getSelectedItem().toString();
        int threshold = 0;
        int threadCount = 1;
        if (!thresholdS3.getText().isBlank())
            threshold = Integer.parseInt(thresholdS3.getText());
        if (!threadCountS3.getText().isBlank())
            threadCount = Integer.parseInt(threadCountS3.getText());

        Complaint complaint = complaintService.getComplaintById(selectedComplaintId);

        if (selectedComplaintId.isBlank() || complaint == null) {
            JOptionPane.showMessageDialog(jPanel3, "Girilen Complaint ID geçersiz!");
        } else {
            List<List<Complaint>> jobs = threadUtil.divideToJob(allData, threadCount);
            List<ThresholdThread> threads = new ArrayList<>();
            ThresholdThread.complaint = complaint;

            for (int i = 0; i < threadCount; i++) {
                ThresholdThread thread = new ThresholdThread("ThresholdThread" + i, stringUtil);
                thread.setPartData(jobs.get(i));
                thread.setSimilarity(threshold);
                thread.setSelectedColumn(selectedColumn);
                threads.add(thread);
            }

            threads.parallelStream().forEach(thread -> {
                thread.start();
            });

            tableUtil.showThreadTable(threadInfoTable,threads);

            List<Threshold> similarityAverages = new ArrayList<>();
            threads.stream().forEach(thread -> {
                similarityAverages.addAll(thread.getThresholds());
            });

            tableUtil.showTableS3(resultTable, similarityAverages,selectedColumn);
        }


    }//GEN-LAST:event_buttonS3ActionPerformed

    private void thresholdS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thresholdS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thresholdS2ActionPerformed

    private void selectedColumnS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedColumnS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedColumnS2ActionPerformed

    private void thresholdS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thresholdS1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_thresholdS1ActionPerformed

    private void selectedColumnS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedColumnS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedColumnS1ActionPerformed


    private void selectedColumn2S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedColumn2S2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedColumn2S2ActionPerformed

    private void threshold2S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threshold2S2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threshold2S2ActionPerformed

    private void threadCountS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threadCountS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threadCountS2ActionPerformed

    private void threadCountS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threadCountS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threadCountS1ActionPerformed


    private void selectedColumnS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedColumnS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedColumnS3ActionPerformed

    private void thresholdS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thresholdS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thresholdS3ActionPerformed

    private void threadCountS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threadCountS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threadCountS3ActionPerformed

    private void complaintIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complaintIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complaintIdActionPerformed

    private void choosenColumnS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosenColumnS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choosenColumnS2ActionPerformed

    private void thresholdS1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thresholdS1KeyTyped
        // TODO add your handling code here:

        char key = evt.getKeyChar();
        if (!Character.isDigit(key)
                || thresholdS1.getText().length() > 2) {
            evt.consume();
        } else {
            int number = Integer.parseInt(thresholdS1.getText() + key);
            if (number > 100) {
                thresholdS1.setText("100");
                evt.consume();
            }
        }


    }//GEN-LAST:event_thresholdS1KeyTyped

    private void threadCountS1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_threadCountS1KeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)) {
            evt.consume();
        }

    }//GEN-LAST:event_threadCountS1KeyTyped

    private void thresholdS2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thresholdS2KeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)
                || thresholdS2.getText().length() > 2) {
            evt.consume();
        } else {
            int number = Integer.parseInt(thresholdS2.getText() + key);
            if (number > 100) {
                thresholdS2.setText("100");
                evt.consume();
            }
        }
    }//GEN-LAST:event_thresholdS2KeyTyped

    private void threshold2S2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_threshold2S2KeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)
                || threshold2S2.getText().length() > 2) {
            evt.consume();
        } else {
            int number = Integer.parseInt(threshold2S2.getText() + key);
            if (number > 100) {
                threshold2S2.setText("100");
                evt.consume();
            }
        }
    }//GEN-LAST:event_threshold2S2KeyTyped

    private void thresholdS3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thresholdS3KeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)
                || thresholdS3.getText().length() > 2) {
            evt.consume();
        } else {
            int number = Integer.parseInt(thresholdS3.getText() + key);
            if (number > 100) {
                thresholdS3.setText("100");
                evt.consume();
            }
        }
    }//GEN-LAST:event_thresholdS3KeyTyped

    private void complaintIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_complaintIdKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)
                || complaintId.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_complaintIdKeyTyped

    private void threadCountS3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_threadCountS3KeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)) {
            evt.consume();
        }
    }//GEN-LAST:event_threadCountS3KeyTyped

    private void threadCountS2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_threadCountS2KeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)) {
            evt.consume();
        }
    }//GEN-LAST:event_threadCountS2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonS1;
    private javax.swing.JButton buttonS2;
    private javax.swing.JButton buttonS3;
    private javax.swing.JComboBox<String> choosenColumnS2;
    private javax.swing.JTextField complaintId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable resultTable;
    private javax.swing.JComboBox<String> selectedColumn2S2;
    private javax.swing.JComboBox<String> selectedColumnS1;
    private javax.swing.JComboBox<String> selectedColumnS2;
    private javax.swing.JComboBox<String> selectedColumnS3;
    private javax.swing.JTextField threadCountS1;
    private javax.swing.JTextField threadCountS2;
    private javax.swing.JTextField threadCountS3;
    private javax.swing.JTable threadInfoTable;
    private javax.swing.JTextField threshold2S2;
    private javax.swing.JTextField thresholdS1;
    private javax.swing.JTextField thresholdS2;
    private javax.swing.JTextField thresholdS3;
    // End of variables declaration//GEN-END:variables
}
