/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.trkgrn_theomer.bigdatathresholding.ui.Test;

import com.trkgrn_theomer.bigdatathresholding.api.model.Complaint;
import com.trkgrn_theomer.bigdatathresholding.api.service.ComplaintService;
import com.trkgrn_theomer.bigdatathresholding.api.utility.CSVUtil;
import lombok.SneakyThrows;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.stream.IntStream;

/**
 * @author trkgrn
 */
@Component
public class Deneme extends javax.swing.JFrame {

    /**
     * Creates new form Deneme
     */

    private final CSVUtil csvUtil;
    private final ComplaintService complaintService;

    public Deneme(CSVUtil csvUtil, ComplaintService complaintService) {
        this.csvUtil = csvUtil;
        this.complaintService = complaintService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        runButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        runButton.setText("RUN");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            @SneakyThrows
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("YAZLAB 2 PROJE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                                .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_runButtonActionPerformed
        System.out.println("Deneme RUN button basıldı");
        csvUtil.createRegularData();
//        complaintService.deleteAll();
//        System.out.println("Sildi");
//        List<File> files = csvUtil.splitRegularDataFile(100000);
//             files.parallelStream().forEach(file -> {
//                 try {
//                     List<Complaint> complaints =  csvUtil.getRegularData(file);
//                     System.out.println(file.getName() +" adlı dosyadan çekilen veri sayısı: "+complaints.size());
////                     IntStream.range(0,complaints.size()).parallel().forEach(index -> {
////                         complaintService.save(complaints.get(index));
////                     });
//                        complaintService.saveAll(complaints);
//                     System.out.println(file.getName() +" adlı dosyadan çekilen veriler kaydedildi");
//                 } catch (IOException e) {
//                     e.printStackTrace();
//
//                 }
//
//             });
        //   complaintService.saveAll(csvUtil.getAllRegularData());
        System.out.println("Bitti");
    }//GEN-LAST:event_runButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
}
